Localization full
BeloMaximka/MystatDesktopWpf pull request #18
Opened 2022-11-06 11:00 UTC by zuzeyka

Подвязку допилю чуть позже, пока 3 языковых файла, если вдруг что-то упустил - дайте знать

2022-11-06 11:01 UTC, zuzeyka commented
![](https://github.trello.services/images/mini-trello-icon.png) [Локализация на украинском](https://trello.com/c/n63za2gz/62-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BD%D0%B0-%D1%83%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%81%D0%BA%D0%BE%D0%BC)

2022-11-06 11:01 UTC, zuzeyka commented
![](https://github.trello.services/images/mini-trello-icon.png) [Локализация на русском](https://trello.com/c/PiWexdTK/71-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BD%D0%B0-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC)

2022-11-06 11:02 UTC, zuzeyka commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать смену языка](https://trello.com/c/GXPTfanY/64-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%81%D0%BC%D0%B5%D0%BD%D1%83-%D1%8F%D0%B7%D1%8B%D0%BA%D0%B0)

2022-11-06 11:02 UTC, zuzeyka commented
![](https://github.trello.services/images/mini-trello-icon.png) [Локализация на английском](https://trello.com/c/lqlWisoQ/63-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BD%D0%B0-%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%BE%D0%BC)

2022-11-06 12:07 UTC, DDeenis commented on MystatDesktopWpf/App.xaml.cs
> +        public static List<CultureInfo> Languages
Можно сократить до `public static List<CultureInfo> Languages { get; private set; }`

2022-11-06 12:19 UTC, DDeenis submitted a review, later dismissed

2022-11-06 12:20 UTC, DDeenis commented on MystatDesktopWpf/App.xaml.cs
> +                ResourceDictionary oldDict = (from d in Application.Current.Resources.MergedDictionaries
Может будем использовать функции вместо этого синтаксиса?

2022-11-06 13:07 UTC, BeloMaximka requested changes
Убедись, что все ключи в файлах локализации уникальные

2022-11-06 13:07 UTC, BeloMaximka commented on MystatDesktopWpf/Languages/lang.en-US.xaml
> +    <v:String x:Key="m_SettingsOfNotification1">When to remind:</v:String>
одинаковые ключи m_SettingsOfNotification1

2022-11-06 13:07 UTC, BeloMaximka commented on MystatDesktopWpf/Languages/lang.ru-RU.xaml
> +    <v:String x:Key="m_SettingsOfNotification1">Когда напоминать:</v:String>
одинаковые ключи m_SettingsOfNotification1

2022-11-06 13:07 UTC, BeloMaximka commented on MystatDesktopWpf/Languages/lang.ua-UA.xaml
> +    <v:String x:Key="m_SettingsOfNotification1">Коли нагадувати:</v:String>
одинаковые ключи m_SettingsOfNotification1

2022-11-06 16:48 UTC, BeloMaximka commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать базовую систему для работы с локализацией](https://trello.com/c/etK4V1it/77-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D1%83%D1%8E-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%83-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B5%D0%B9)

2022-11-08 22:04 UTC, DDeenis approved these changes

2022-11-08 22:04 UTC, BeloMaximka approved these changes

2022-11-08 22:04 UTC, merged